// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBpLESI178anNrhFetEY1FRkVQXeByLZU',
    appId: '1:579306392370:web:eb4e6355134377dc68252b',
    messagingSenderId: '579306392370',
    projectId: 'habit-flow-79f0a',
    authDomain: 'habit-flow-79f0a.firebaseapp.com',
    storageBucket: 'habit-flow-79f0a.firebasestorage.app',
    measurementId: 'G-636KY7Q7EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPHa_36JeA_qyBG6oK63XmhVS8CUZ7ma8',
    appId: '1:579306392370:android:abe8e5cb81a72f4c68252b',
    messagingSenderId: '579306392370',
    projectId: 'habit-flow-79f0a',
    storageBucket: 'habit-flow-79f0a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUsbGJL2fFjCT0MWHakMc717C31M9YcCY',
    appId: '1:579306392370:ios:704bd43718e1439968252b',
    messagingSenderId: '579306392370',
    projectId: 'habit-flow-79f0a',
    storageBucket: 'habit-flow-79f0a.firebasestorage.app',
    iosClientId:
        '579306392370-rlbab9fc3pu0drbssasrblfioaomfr0n.apps.googleusercontent.com',
    iosBundleId: 'com.ilhaaam24.habitFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUsbGJL2fFjCT0MWHakMc717C31M9YcCY',
    appId: '1:579306392370:ios:704bd43718e1439968252b',
    messagingSenderId: '579306392370',
    projectId: 'habit-flow-79f0a',
    storageBucket: 'habit-flow-79f0a.firebasestorage.app',
    iosClientId:
        '579306392370-rlbab9fc3pu0drbssasrblfioaomfr0n.apps.googleusercontent.com',
    iosBundleId: 'com.ilhaaam24.habitFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBpLESI178anNrhFetEY1FRkVQXeByLZU',
    appId: '1:579306392370:web:a5bfc064a53cf88368252b',
    messagingSenderId: '579306392370',
    projectId: 'habit-flow-79f0a',
    authDomain: 'habit-flow-79f0a.firebaseapp.com',
    storageBucket: 'habit-flow-79f0a.firebasestorage.app',
    measurementId: 'G-SPTYPSG8LN',
  );
}
